/*
 * colors.h
 * Description:
 *
 *  Created on: Dec 17, 2018
 *      Author: Cody
 */

#ifndef COLORS_H_
#define COLORS_H_


#include <stdlib.h> // used for random color generation
#include <time.h>  	// used for random color generation
#include <stdint.h>

// Random selection will choose the color that is picked for display
typedef enum {Red, Blue, Green, Purple, Orange, White, none } color_selected;

// Color object
typedef struct{
    color_selected picked; // Color picked by RandomColor generator
    int8_t *colorText;
    color_selected LEDColor;
}drawn_color;

// Initialize the color object
void initColor(drawn_color *m_color);

// This function will pick a random color and assign it the appropriate String
void RandomColor(drawn_color *);

// Function determines if the randomly color displayed on the LCD  matches the color generated by the LCD
// bool colorsMatched

#endif /* COLORS_H_ */
